Importing all packages needed: pandas, matplotlib, seaborn and sqlite.

In [15]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3

In [16]:
#reading dataset bird_strikes.csv to pandas as df
df = pd.read_csv('bird_strikes.csv', keep_default_na=False) #arg so "None" would not be null value

df.info()  #displaying basic info on dataframe df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25429 entries, 0 to 25428
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   RecordID                  25429 non-null  int64
 1   AircraftType              25429 non-null  object
 2   AirportName               25429 non-null  object
 3   AltitudeBin               25429 non-null  object
 4   MakeModel                 25429 non-null  object
 5   NumberStruck              25429 non-null  object
 6   NumberStruckActual        25429 non-null  int64
 7   Effect                    25429 non-null  object
 8   FlightDate                25429 non-null  object
 9   Damage                    25429 non-null  object
 10  Engines                   25429 non-null  object
 11  Operator                  25429 non-null  object
 12  OriginState               25429 non-null  object
 13  FlightPhase               25429 non-null  object
 14  ConditionsPrecipitation   25429 non-null  object
 15  RemainsCollected?         25429 non-null  bool
 16  RemainsSentToSmithsonian  25429 non-null  bool
 17  Remarks                   25429 non-null  object
 18  WildlifeSize              25429 non-null  object
 19  ConditionsSky             25429 non-null  object
 20  WildlifeSpecies           25429 non-null  object
 21  PilotWarned               25429 non-null  object
 22  Cost                      25429 non-null  object
 23  Altitude                  25429 non-null  int64
 24  PeopleInjured             25429 non-null  int64
 25  IsAircraftLarge?          25429 non-null  object
dtypes: bool(2), int64(4), object(20)
memory usage: 4.7+ MB

In [17]:
#dropping columns in df
df.drop(columns=[
    'AircraftType', 'AltitudeBin', 'NumberStruck',
    'NumberStruckActual', 'Engines', 'RemainsSentToSmithsonian',
    'RemainsCollected?', 'WildlifeSize', 'PilotWarned',
    'IsAircraftLarge?'], axis=1, inplace=True)
df.columns #listing columns to confirm if drop was succesful

Index(['RecordID', 'AirportName', 'MakeModel', 'Effect', 'FlightDate',
       'Damage', 'Operator', 'OriginState', 'FlightPhase',
       'ConditionsPrecipitation', 'Remarks', 'ConditionsSky',
       'WildlifeSpecies', 'Cost', 'Altitude', 'PeopleInjured'],
      dtype='object')

In [18]:
#renaming columns in df
df.rename(columns={
    'AirportName': 'Airport',
    'Operator': 'Airline',
    'OriginState': 'State',
    'ConditionsPrecipitation': 'Precipitation',
    'ConditionsSky': 'Clouds',
    'WildlifeSpecies': 'BirdSpecies'}, inplace=True) 

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25429 entries, 0 to 25428
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   RecordID       25429 non-null  int64
 1   Airport        25429 non-null  object
 2   MakeModel      25429 non-null  object
 3   Effect         25429 non-null  object
 4   FlightDate     25429 non-null  object
 5   Damage         25429 non-null  object
 6   Airline        25429 non-null  object
 7   State          25429 non-null  object
 8   FlightPhase    25429 non-null  object
 9   Precipitation  25429 non-null  object
 10  Remarks        25429 non-null  object
 11  Clouds         25429 non-null  object
 12  BirdSpecies    25429 non-null  object
 13  Cost           25429 non-null  object
 14  Altitude       25429 non-null  int64
 15  PeopleInjured  25429 non-null  int64
dtypes: int64(3), object(13)
memory usage: 3.1+ MB

In [19]:
df.isnull().sum() #checking for null values in df

RecordID         0
Airport          0
MakeModel        0
Effect           0
FlightDate       0
Damage           0
Airline          0
State            0
FlightPhase      0
Precipitation    0
Remarks          0
Clouds           0
BirdSpecies      0
Cost             0
Altitude         0
PeopleInjured    0
dtype: int64

In [20]:
df.head()

,RecordID,Airport,MakeModel,Effect,FlightDate,Damage,Airline,State,FlightPhase,Precipitation,Remarks,Clouds,BirdSpecies,Cost,Altitude,PeopleInjured
0,202152,LAGUARDIA NY,B-737-400,Engine Shut Down,11/23/2019 0:00,Caused damage,US AIRWAYS*,New York,Climb,None,FLT 753. PILOT REPTD A HUNDRED BIRDS ON UNKN T...,No Cloud,Unknown bird - medium,"30,736",1500,0
1,208159,DALLAS/FORT WORTH INTL ARPT,MD-80,None,7/25/2019 0:00,Caused damage,AMERICAN AIRLINES,Texas,Landing Roll,None,102 CARCASSES FOUND. 1 LDG LIGHT ON NOSE GEAR ...,Some Cloud,Rock pigeon,0,0,0
2,207601,LAKEFRONT AIRPORT,C-500,None,9/14/2019 0:00,No damage,BUSINESS,Louisiana,Approach,None,FLEW UNDER A VERY LARGE FLOCK OF BIRDS OVER AP...,No Cloud,European starling,0,50,0
3,215953,SEATTLE-TACOMA INTL,B-737-400,Precautionary Landing,9/5/2019 0:00,No damage,ALASKA AIRLINES,Washington,Climb,None,"NOTAM WARNING. 26 BIRDS HIT THE A/C, FORCING A...",Some Cloud,European starling,0,50,0
4,219878,NORFOLK INTL,CL-RJ100/200,None,6/23/2020 0:00,No damage,COMAIR AIRLINES,Virginia,Approach,None,NO DMG REPTD.,No Cloud,European starling,0,50,0

In [21]:
#reading in the second dataset airport.csv to pandas
df2 = pd.read_csv('airport.csv')

df2.info()  #displaying basic info on dataframe df2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7698 entries, 0 to 7697
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               7698 non-null   int64
 1   name             7698 non-null   object
 2   city             7649 non-null   object
 3   country          7698 non-null   object
 4   iata             7698 non-null   object
 5   icao             7698 non-null   object
 6   latitude         7698 non-null   float64
 7   longitude        7698 non-null   float64
 8   altitude         7698 non-null   int64
 9   timezone_offset  7698 non-null   object
 10  dst              7698 non-null   object
 11  timezone         7698 non-null   object
 12  type             7698 non-null   object
 13  source           0 non-null      float64
dtypes: float64(3), int64(2), object(9)
memory usage: 842.1+ KB

In [22]:
#dropping columns in df2
df2 = df2.drop(columns=['timezone_offset', 'dst', 'timezone', 'type', 'source'])
df2.columns #listing columns to confirm if drop was succesful

Index(['id', 'name', 'city', 'country', 'iata', 'icao', 'latitude',
       'longitude', 'altitude'],
      dtype='object')

In [23]:
#renaming 'name' column in df2 to 'airport'
df2.rename(columns={
    'name': 'airport'
    }, inplace=True)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7698 entries, 0 to 7697
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         7698 non-null   int64
 1   airport    7698 non-null   object
 2   city       7649 non-null   object
 3   country    7698 non-null   object
 4   iata       7698 non-null   object
 5   icao       7698 non-null   object
 6   latitude   7698 non-null   float64
 7   longitude  7698 non-null   float64
 8   altitude   7698 non-null   int64
dtypes: float64(2), int64(2), object(5)
memory usage: 541.4+ KB

In [24]:
df2.isnull().sum() #checking for null values in df2

id            0
airport       0
city         49
country       0
iata          0
icao          0
latitude      0
longitude     0
altitude      0
dtype: int64

In [25]:
df2.head()

,id,airport,city,country,iata,icao,latitude,longitude,altitude
0,1,Goroka Airport,Goroka,Papua New Guinea,GKA,AYGA,-6.081690,145.391998,5282
1,2,Madang Airport,Madang,Papua New Guinea,MAG,AYMD,-5.207080,145.789001,20
2,3,Mount Hagen Kagamuga Airport,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826790,144.296005,5388
3,4,Nadzab Airport,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569803,146.725977,239
4,5,Port Moresby Jacksons International Airport,Port Moresby,Papua New Guinea,POM,AYPY,-9.443380,147.220001,146

This function: values() is designed to list any value counts of columns in the df you wish to display. By default it will list all data "limit=None" unless you pass in the arg ".head(limit)" the number of records you wish to display. For example: values(df, 'column_name', 8) would display the top 8 most frequent values in df and the column you choose.

In [26]:
def values(df, column_name, limit=None):
    counts = df[column_name].value_counts()
    if limit is not None:
        print(counts.head(limit))
    else:
        print(counts)

In [27]:
values(df, 'FlightPhase')

FlightPhase
Approach        10382
Landing Roll     5047
Take-off run     4711
Climb            4429
Descent           776
Taxi               74
Parked             10
Name: count, dtype: int64